name: Build aarch64_generic

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "插件名"
        required: false
        default: "luci-app-ssr-plus"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
      - uses: actions/checkout@v4

      #- name: 清理磁盘
       # uses: jlumbroso/free-disk-space@main

      #- name: 安装依赖
       # run: sudo apt update && sudo apt install -y build-essential libncurses-dev git wget unzip

       - name: 下载SDK
        run: |
          FILE="/releases/24.10.1/targets/armsr/armv8/immortalwrt-sdk-24.10.1-armsr-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          MIRRORS=(
            "https://downloads.immortalwrt.org"
            "https://mirrors.zju.edu.cn/immortalwrt"
            "https://mirrors.ustc.edu.cn/immortalwrt"
            "https://mirror.sjtu.edu.cn/immortalwrt"
          )
          for url in "${MIRRORS[@]}"; do
            echo "尝试下载: $url/$FILE"
            aria2c -x 8 -s 8 --timeout=60 --retries=3 "$url/$FILE" && break
          done
          mkdir -p sdk
          tar -xJf immortalwrt-sdk-*.tar.xz --strip-components=1 -C sdk

      - name: 安装 feeds
        run: |
          cd sdk
          echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
          ./scripts/feeds update -a && ./scripts/feeds install -a
          make defconfig

      - name: 编译插件
        run: |
          cd sdk
          make package/${{ inputs.packages }}/download V=s -j$(nproc)
          make package/${{ inputs.packages }}/compile V=s -j$(nproc)

      - name: 上传插件
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: sdk/bin/packages/aarch64_generic/helloworld/*.ipk
